# Generated by Django 5.0.1 on 2024-03-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_review_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='borrowing_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
