# Generated by Django 5.0.1 on 2024-03-06 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_review_user'),
        ('reglogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='reglogin.useraccount'),
        ),
    ]
